apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap1
data:
  logging.conf: |
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    level: INFO
    filename: %hostname-%timestamp.log