apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - image: busybox
      name: mypod
      args:
      - /bin/sh
      - -c
      - sleep 10; touch /tmp/healthy; sleep 30000
      volumeMounts:
      - mountPath: "/etc/foo"
        name: foo
        readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: mysecret4
        items:
        - key: username
          path: my-group/my-username
        - key: password
          path: my-group/my-password