apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - image: busybox
      name: mypod
      args:
      - /bin/sh
      - -c
      - sleep 10; touch /tmp/healthy; sleep 30000
      volumeMounts:
      - mountPath: "/etc"
        name: foo
  volumes:
    - name: foo
      configMap:
        name: myconfigmap1
        items:
          - key: logging.conf
            path: myapp/logging.conf